[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
todo_list_app = "HVo1Tzq8emezXRMfhbfbFf7fAjom3QmDMYnCcE6TKYJq"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/Users/oghenekarouzezi/Documents/web3/learning/solana/tokens/solana-nft-anchor/kBNoW8gnsPwsfnpfDm8oVmPJ5uANha32fadNoWn6iao.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
